### PR TITLE
Fix formatting of last session on user stats page

### LINKED ISSUE #26: Formatting of last session on user stats page is wrong
e.g. shows "2 Oct 01:25" when it should be 26 Oct 01:25, also perhaps rethink this formatting.

### PR DESCRIPTION
**Pull request by hulthe**
resolves #26

### CODE REVIEW

File: frontend/src/dateUtil.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export function isToday(date: Date): boolean {
 }
 
 export function formatDate(date: Date): string {
-  return `${date.getDay()} ${date.toLocaleString('default', {
+  return `${date.getDate()} ${date.toLocaleString('default', {
```
Comment (ViddeM) [inline frontend/src/dateUtil.ts:61]: You sure you don't want to use "date.getTheRealFuckingDateNoIMeanForRealFuckOffJavascriptIHateYou()" instead?

**Review by ViddeM — APPROVED** [review]
No but for real, nicely done! :+1:
